### ISSUE TITLE
Absolute URL being used as relative path

### ISSUE THREAD

**Issue by lindseydiloreto** [mikhail-guru/pdfthumb#1]
My Twig code looks almost exactly like the example code, yet I'm getting this error:

> filemtime(): stat failed for /Users/lindseydiloreto/Sites/industrialassets/iamachinery/public/http://import.test/assets/brochures/0311.pdf

Clearly it's trying to read my **absolute** URL as a relative path... Is this a bug, or do I need to do something differently?

```
{% set pdf = entry.brochurePdf.first %}

<img src="{{ pdfthumb.get(pdf.url, {width: 470}) }}" />
```

**Comment by m-emelchenkov** [comment]
"pdf.url" should return relative URL, not absolute. I use Assets field type to select PDF file when editing page, and it returns relative URL.

**Comment by lindseydiloreto** [comment]
Actually, that's not entirely true. I believe `pdf.url` will follow whatever format you've entered into the "URL" setting for your asset source.

It's quite common for the asset's `url` to be an absolute URL... take a look at the official docs:

> http://buildwithcraft.com/docs/multi-environment-configs#example-multi-environment-asset-source-settings

Could you possibly make this plugin compatible with absolute URLs?

**Comment by m-emelchenkov** [comment]
Got it. Will see what can I do.

**Comment by lindseydiloreto** [comment]
Thanks.

**Comment by lindseydiloreto** [comment]
Don't worry about this... I've decided to write my own plugin to handle my specific needs.

Thanks anyway!

**Comment by m-emelchenkov** [comment]
I can offer you to take control over my repository, you will be the maintainer of this plugin. Also, I can share some portion of code which will help you to implement what you want but anyway you need to re-write whole plugin to support multi-site configurations.

**Comment by lindseydiloreto** [comment]
Hmm, very interesting... I appreciate the offer, let me think about that and get back to you!

**Comment by lindseydiloreto** [comment]
Hi Mikhail,

I've put a lot of thought into your offer, and I'm afraid I have to decline.

I've already started working on my own plugin to handle this need, and it's quite different from what you've built. With all due respect, I'd prefer to continue evolving the plugin that I've started. While it's very kind and generous of you, I don't believe it's the right fit for me.

Thanks, best of luck to you!

**Comment by bgarrant** [comment]
Any fix for the Absolute URL issue?  I have having troubles with it as well anbd can't seem to get around it.  Using rerlative URL for an asset field URL is breaking image transforms.

**Comment by m-emelchenkov** [comment]
@bgarrant how it is breaking image transforms? I use transformations too but it works on my setup. Please write more detailed explanation in order to understand what not working currently.

**Comment by bgarrant** [comment]
I think thaty issue is unrelated.  Just found a bug in latest version of Craft with extension are in CAPS like JPG instead of jpg

**Comment by bgarrant** [comment]
Brad is working on a fix for that

**Comment by m-emelchenkov** [comment]
@lindseydiloreto It's a great choice, because sometimes it's easier to write your own fully customised code than modify someone's else plugin. I hope my plugin helped you to get idea how PDF thumbnails can be implemented in Craft. Anyway, I've added this feature request to To-Do list.
