### ISSUE TITLE
Issue with PDF Thumb Generation when Toggled Layers are Shown

### ISSUE THREAD

**Issue by bgarrant** [mikhail-guru/pdfthumb#2]
I have a PDF that would not generate the PDF Thuimb.  It had layers that could be toggled on and off.  Any idea why it would not work?  I would be happy to send you the PDF.  Looks like this:

![capture](https://cloud.githubusercontent.com/assets/2436728/9236843/5f9c99fa-4115-11e5-90ea-1d2953173528.jpg)

**Comment by m-emelchenkov** [comment]
Yes, feel free to send me. Email on my website, website address in profile.

**Comment by m-emelchenkov** [comment]
After investigating the problem was found. It's a bug in ImageMagick PHP library, in its `resize` function. As a workaround the PDF was flattened and re-saved in Acrobat, then it proceed well.
