### ISSUE TITLE
PDFThumb resulting in image with just a black background

### ISSUE THREAD

**Issue by bgarrant** [mikhail-guru/pdfthumb#3]
I have verified we have latest ImageMagick installed and for some reason I just get a 1KB Black image when PDFThumb is called.  Any idea why?

**Comment by m-emelchenkov** [comment]
@bgarrant Is it black for any PDF or not? Because we had the similar issue in https://github.com/m-emelchenkov/pdfthumb/issues/2, it was a bug in ImageMagick PHP library. Please check if it is the same or not.

**Comment by bgarrant** [comment]
Seems to be all new PDFs.  I tried like 5 of them and just look all black.  This is what I am using.

Version: ImageMagick 6.7.8-9 2014-04-01 Q16 http://www.imagemagick.org

Copyright: Copyright (C) 1999-2012 ImageMagick Studio LLC

Features: OpenMP

Bryan Garrant

Senior Web Designer & Developer

---

Garrant Consulting LLC

3 Meadowview Lane

Massena, NY 13662-4247

Tel: 518.327.5159

Fax: 518.375.3613

**Comment by bgarrant** [comment]
I can provide credentials if you want to test in Craft.

Bryan Garrant

Senior Web Designer & Developer

---

Garrant Consulting LLC

3 Meadowview Lane

Massena, NY 13662-4247

Tel: 518.327.5159

Fax: 518.375.3613

**Comment by bgarrant** [comment]
This is what is being generated with this code:

{% set params = { width: 250, height: 250 } %}

{% for asset in entry.homeFloorplan.kind('pdf') %}

```
   <a href="{{ asset.url }}"><img src="{{ pdfthumb.get(asset.url, params) }}" alt="{{ asset.title }}"></a>
```

{% endfor %}

Bryan Garrant

Senior Web Designer & Developer

---

Garrant Consulting LLC

3 Meadowview Lane

Massena, NY 13662-4247

Tel: 518.327.5159

Fax: 518.375.3613

**Comment by m-emelchenkov** [comment]
Please send me PDF. Email on my website, website address in profile.

**Comment by m-emelchenkov** [comment]
It's the same bug as issue #2. I have fixed it.
