### ISSUE TITLE
Unable to open image. Using relative error.

### ISSUE THREAD

**Issue by mrnebbi** [mikhail-guru/pdfthumb#7]
I'm running my Craft build locally using MAMP and using a .com address. PDF file is accessible with http: added to the below address, but the plugin doesn't seem to be using it. It's trying to access it without (no doubt to prevent HTTP/S issues). How can I fix this and get it to pick up the correct file location?

**Internal Server Error**
unable to open image `//www.WEBSITEADDRESS.com/uploads/pdf/PDF-test-file.pdf': No such file or directory @ error/blob.c/OpenBlob/2695

**Comment by m-emelchenkov** [comment]
Ian, the plugin does add anything special to the address. Please look into PdfthumbService.php at function _populateFSPath(), that function builds a path to PDF. It does not use HTTP/HTTPS address, it builds local file path. Can you debug values of $_SERVER['DOCUMENT_ROOT'] and $element->url? It seems it works in some different way than Linux stack. I use Vagrant with Linux VM to develop, so can't check your setup right now.

**Comment by mrnebbi** [comment]
Hi @m-emelchenkov, I have the following responses.

Docroot: /Applications/MAMP/htdocs/[sitename]/public_html - ElemURL: http://www.[sitename].com/uploads/pdf/PDF-test-file.pdf

**Comment by m-emelchenkov** [comment]
Currently, $element->url should contain relative URL, something like /uploads/pdf/PDF-test-file.pdf. Then it will work.

**Comment by mrnebbi** [comment]
@m-emelchenkov, if I set a str_replace in the _populateFSPath function it progresses to the next part with the correct path. However I then get the following error.

ImagickException

`FailedToExecuteCommand `"/Applications/MAMP/Library/bin/gs" -q -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 "-sDEVICE=pngalpha" -dTextAlphaBits=4 -dGraphicsAlphaBits=4 "-r300x300" -dFirstPage=1 -dLastPage=1 "-sOutputFile=/var/tmp/magick-102053Vwxp4a6Wrxe%d" "-f/var/tmp/magick-10205bnmonNRuPX6T" "-f/var/tmp/magick-1020570it3DTHe5H0"' (-1) @ error/delegate.c/ExternalDelegateCommand/483`

Does that help?

**Comment by m-emelchenkov** [comment]
Nope, I don't know what this error means. Failed to run Ghostscript...  You can to google and try to investigate something. But, I believe you doing the whole process in a counter-productive way:
1. You should use relative URLs.
2. You should not use MAMP. You already got troubles with ImageMagick and believe me, you will get into troubles later with other libraries and incompatibilities between them. For development you should use the same OS which you will use for production--or you will spend hours trying to fix incompatibilities between different PHP and library versions and its configuration options.

However, I will accept patch if you will write a code to support absolute URLs. You need to check URL first, if it is absolute or not, then compare it with siteUrl variable, then strip siteUrl from it.

And I will update the Readme regarding issues with MAMP, if you will find out what's wrong there.

**Comment by mrnebbi** [comment]
Thanks @m-emelchenkov, it's not usually a huge problem running through MAMP for development, but this is clearly causing problems. I think I'll wait to see how it runs on the live server and park it for now. Hopefully it'll just work when it's in place. If I get the time I'll try to work out how to get it running in MAMP and provide you a pull request.

**Comment by mrnebbi** [comment]
Appreciate the quick support 👍
